version: '3.3'
services:
  mysql-container:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./local-app/mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  frontend:
    image: frontend-image:0.2

    ports:
      - "3000:3000"
    depends_on:
      - backend
    
  backend:
    image: backend-image:0.5
    environment:
      - DB_HOST=mysql-container
    ports:
      - "3002:3002"
    depends_on:
      - mysql-container
