version: '3.3'
services:
  mysql-container:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./local-app/mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql