# test if it can handle sudden large spikes in load generated by users


## large number of users and requests in short amount of time

#big amount of users and reqs for a little bit
# realistic spikes

from locust import HttpUser, task, FastHttpUser

class SpikePageRequestsUser(HttpUser):
    host = 'http://192.168.1.216:3000'
    users = 2500 # dont know how many users would be a lot
    spawn_rate = 250 # idem, dont know what spawn rate would be good
    run_time = 1200 # string or int? # again, dont know what would be a good time

    @task
    def dashboard(self):
        self.client.get("/")

    @task
    def products(self):
        self.client.get('/products')

    @task
    def about(self):
        self.client.get('/about')
    
    @task
    def login(self):
        self.client.get('/login')

