# test if it can handle sudden large spikes in load generated by users

## large number of users and requests in short amount of time

#big amount of users and reqs for a little bit

from locust import HttpUser, task, FastHttpUser

class SpikePageRequestsUser(HttpUser):


    @task
    def dashboard(self):
        self.client.get("/")

    @task
    def products(self):
        self.client.get('/products')

    @task
    def about(self):
        self.client.get('/about')
    
    @task
    def login(self):
        self.client.get('/login')

