name: Github Actions Webshop App Demo
run-name: ${{ github.actor }} testing github actions
on: [push]
jobs:
  run-backend-unit-tests:
    runs-on: ubuntu-latest
    services: 
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: ta_test_db
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpw
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_PORT: 3306
        ports:
          - 3306:3306
        # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        volumes:
          - ./local-app/mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    steps:

    - uses: actions/checkout@v3
    - name: schow current directory
      run: echo $GITHUB_WORKSPACE
    - name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: install dependencies
      working-directory: local-app/express-backend
      run: npm install

    - name: run backend server in background
      working-directory: local-app/express-backend
      run: node server.js &

    - run: ps

    - name: identify PID for backend server
      run: |
        server_pid=$(pgrep -f 'node server.js')
        echo "server PID: $server_pid"

    - name: run backend tests
      working-directory: local-app/express-backend
      run: npm run test

    - name: kill backend server
      if: always()
      run: |
        if [[ -n "$server_pid" ]]; then
          kill -2 "$server_pid"
        else
          echo "server pid not found, may already have exited"
        fi

    - run: echo "job status is ${{ job.status }}"






      # - name: list files in repo
      #   run: | 
      #     ls ${{ github.workspace }}
      # - run: pwd
      # # - name: install dependencies backend/
      #   # run: cd local-app/express-backend/
      # - name: install dependencies
      #   run: npm install
      #   working-directory: local-app/express-backend/
      # - name: run server
      #   run: node server.js
      #   working-directory: local-app/express-backend/
      # - name: execute tests
      #   run: npm run test
      #   working-directory: local-app/express-backend/





  # explore-github-actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: 
  #     - name: check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "${{ github.repository }} has been cloned to runner"
  #     - run: echo "workflow ready to test code on hte runner"
  #     - name: list files in repo
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "job status is ${{ job.status }}"