name: Github Actions Webshop App Demo
run-name: ${{ github.actor }} testing github actions
on: [push]
jobs:
  run-backend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: cd ./local-app/express-backend
      - run: npm install
      - run: node server.js
      - run: npm run test
  # explore-github-actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: 
  #     - name: check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "${{ github.repository }} has been cloned to runner"
  #     - run: echo "workflow ready to test code on hte runner"
  #     - name: list files in repo
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "job status is ${{ job.status }}"