name: Github Actions Webshop App Demo
run-name: ${{ github.actor }} testing github actions
on: [push]
jobs:
  run-backend-unit-tests:
    runs-on: ubuntu-latest
    # services: 
    #   mysql:
    #     image: mysql:latest
    #     env:
    #       MYSQL_DATABASE: ta_test_db
    #       MYSQL_ROOT_PASSWORD: rootpw
    #       MYSQL_USER: testuser
    #       MYSQL_PASSWORD: testpw
    #     ports:
    #       - 3306:3306
    #     # Before continuing, verify the mysql container is reachable from the ubuntu host
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: schow current directory
      run: echo $GITHUB_WORKSPACE
    - name: list files
      run: |
        pwd
        ls -la
    - name: change working dir
      working-directory: local-app/express-backend
      run: |
        pwd
        ls -la





      # - name: list files in repo
      #   run: | 
      #     ls ${{ github.workspace }}
      # - run: pwd
      # # - name: install dependencies backend/
      #   # run: cd local-app/express-backend/
      # - name: install dependencies
      #   run: npm install
      #   working-directory: local-app/express-backend/
      # - name: run server
      #   run: node server.js
      #   working-directory: local-app/express-backend/
      # - name: execute tests
      #   run: npm run test
      #   working-directory: local-app/express-backend/





  # explore-github-actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: 
  #     - name: check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "${{ github.repository }} has been cloned to runner"
  #     - run: echo "workflow ready to test code on hte runner"
  #     - name: list files in repo
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "job status is ${{ job.status }}"