name: run tests on push
run-name: ${{ github.actor }} running tests on push
on: [ push ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: run unittests
        uses: ./.github/actions/run-unit-tests.yml
    